#!/usr/bin/env bash
# Redirection
sudo apt-get  update
sudo apt-get  install nginx -y
echo "Hello World!" > sudo tee /var/www/html/index.html

# Use double quotes around the sed command and use a different delimiter
sudo sed -i "/server_name _;/a \\\trewrite ^/redirect_me http://www.github.com permanent;" /etc/nginx/sites-available/default

# Start Nginx service
sudo service nginx start
