#!/usr/bin/env bash
#tells a story based on the contents of the `/etc/passwd` file
f="/etc/passwd"
f1=""
f2=""
f3=""
while IFS= read -r l
do
    f1="$(echo "$l" | cut -d":" -f1)"
    f2="$(echo "$l" | cut -d":" -f4)"
    f3="$(echo "$l" | cut -d":" -f6)"
    f4="$(echo "$l" | cut -d":" -f7)"
    f5="$(echo "$l" | cut -d":" -f3)"
    f6="$(echo "$l" | cut -d":" -f2)"
    f7="$(echo "$l" | cut -d":" -f5)"
    echo "The user ${f1} is part of the ${f2} gang, lives in ${f3} and rides ${f4}. ${f5}'s place is protected by the passcode ${f6}, more info about the user here: ${f7}"
done < "$f"
